---
- name: Re-Register Checkmk Agents via Headscale VPN
  hosts: lenovo_vms, dedicated, Hostinger, wazuh
  remote_user: ansible
  become: true

  vars:
    cmk_site: "monitoring"
    cmk_registration_server: "100.64.0.5:8000"
    cmk_user: "automation"

  tasks:
    - name: Check if host should be processed
      ansible.builtin.meta: end_host
      when: headscale_ip is not defined or inventory_hostname == 'monitoring'

    - name: Ensure cmk-agent-ctl command is available
      ansible.builtin.command: which cmk-agent-ctl
      changed_when: false
      ignore_errors: true
      register: agent_ctl_check

    - name: Skip host if Checkmk agent is not installed
      ansible.builtin.meta: end_host
      when: agent_ctl_check.rc != 0

    - name: Purge old Checkmk TLS registration
      ansible.builtin.command: cmk-agent-ctl delete-all
      ignore_errors: true 

    - name: Register Agent with new Checkmk Server (TLS)
      ansible.builtin.command: >
        cmk-agent-ctl register 
        --hostname {{ inventory_hostname }} 
        --server {{ cmk_registration_server }} 
        --site {{ cmk_site }} 
        --user {{ cmk_user }} 
        --password "{{ cmk_secret }}" 
        --trust-cert
